version: '3.8'

services:
  spring-app:
    image: messikhaymen/g-sante:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/GMT
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=aymenmessikh2002

  db:
    image: postgres
    environment:
      POSTGRES_DB: GMT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aymenmessikh2002
    ports:
      - "5432:5432"
